### ISSUE TITLE
Predictor.

### ISSUE THREAD

**Issue by TAY-985** [ddlBoJack/HDRR#1]
Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz")
<img width="266" alt="1640681372(1)" src="https://user-images.githubusercontent.com/65696081/147547670-f90b1a7f-8519-47ff-bf5f-d931f37f9359.png">

hello,I meet this bug, why?

**Comment by ddlBoJack** [comment]
Hi, this works on my machine. I guess it's a problem with the library of allennlp. You can download it and manually decompress it as an alternative. Or you can refer to http://docs.allennlp.org/v0.9.0/api/allennlp.predictors.html#allennlp.predictors.predictor.Predictor for detail.
